serviceName: api_gateway_service
grpcClient:
  port: :5003
http:
  port: :5001
  development: true
  basePath: /api/v1
  kreditPath: /api/v1
  debugHeaders: false
  httpClientDebug: false
  debugErrorsResponse: true
  ignoreLogUrls: ["metrics"]
logger:
  encoding: json
  level: debug
  ouputPath: logs
  errorPath: logs
kafka:
  brokers: ["localhost:9092"]
  groupID: api_gateway_consumer
  initTopics: true
kafkaTopics:
  konsumenCreate:
    topicName: konsumen_create
    partitions: 10
    poolSize: 10
    replicationFactor: 1
  limitCreate:
    topicName: limit_create
    partitions: 10
    poolSize: 10
    replicationFactor: 1
  transaksiCreate:
    topicName: transaksi_create
    partitions: 10
    poolSize: 10
    replicationFactor: 1
