serviceName: writer_service
grpc:
  port: :5002
logger:
  encoding: json
  level: debug
  ouputPath: logs
  errorPath: logs
postgres:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  dbName: kredit
  sslMode: false
kafka:
  brokers: ["localhost:9092"]
  groupID: writer_microservice_consumer
  initTopics: true
kafkaTopics:
  konsumenCreate:
    topicName: konsumen_create
    partitions: 10
    poolSize: 10
    replicationFactor: 1
  konsumenCreated:
    topicName: konsumen_created
    partitions: 10
    poolSize: 10
    replicationFactor: 1
  limitCreate:
    topicName: limit_create
    partitions: 10
    poolSize: 10
    replicationFactor: 1
  limitCreated:
    topicName: limit_created
    partitions: 10
    poolSize: 10
    replicationFactor: 1
  transaksiCreate:
    topicName: transaksi_create
    partitions: 10
    poolSize: 10
    replicationFactor: 1
  transaksiCreated:
    topicName: transaksi_created
    partitions: 10
    poolSize: 10
    replicationFactor: 1
