// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: kredit_message.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateKonsumenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nik          string               `protobuf:"bytes,2,opt,name=Nik,json=nik,proto3" json:"Nik,omitempty"`
	FullName     string               `protobuf:"bytes,3,opt,name=FullName,json=full_name,proto3" json:"FullName,omitempty"`
	LegalName    string               `protobuf:"bytes,4,opt,name=LegalName,json=legal_name,proto3" json:"LegalName,omitempty"`
	Gaji         uint64               `protobuf:"varint,5,opt,name=Gaji,json=gaji,proto3" json:"Gaji,omitempty"`
	TempatLahir  string               `protobuf:"bytes,6,opt,name=TempatLahir,json=tempat_lahir,proto3" json:"TempatLahir,omitempty"`
	TanggalLahir *timestamp.Timestamp `protobuf:"bytes,7,opt,name=TanggalLahir,json=tanggal_lahir,proto3" json:"TanggalLahir,omitempty"`
	FotoKtp      string               `protobuf:"bytes,8,opt,name=FotoKtp,json=foto_ktp,proto3" json:"FotoKtp,omitempty"`
	FotoSelfie   string               `protobuf:"bytes,9,opt,name=FotoSelfie,json=foto_selfie,proto3" json:"FotoSelfie,omitempty"`
	Role         string               `protobuf:"bytes,10,opt,name=Role,json=role,proto3" json:"Role,omitempty"`
	Email        string               `protobuf:"bytes,11,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password     string               `protobuf:"bytes,12,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
}

func (x *CreateKonsumenRequest) Reset() {
	*x = CreateKonsumenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKonsumenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKonsumenRequest) ProtoMessage() {}

func (x *CreateKonsumenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKonsumenRequest.ProtoReflect.Descriptor instead.
func (*CreateKonsumenRequest) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKonsumenRequest) GetNik() string {
	if x != nil {
		return x.Nik
	}
	return ""
}

func (x *CreateKonsumenRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateKonsumenRequest) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *CreateKonsumenRequest) GetGaji() uint64 {
	if x != nil {
		return x.Gaji
	}
	return 0
}

func (x *CreateKonsumenRequest) GetTempatLahir() string {
	if x != nil {
		return x.TempatLahir
	}
	return ""
}

func (x *CreateKonsumenRequest) GetTanggalLahir() *timestamp.Timestamp {
	if x != nil {
		return x.TanggalLahir
	}
	return nil
}

func (x *CreateKonsumenRequest) GetFotoKtp() string {
	if x != nil {
		return x.FotoKtp
	}
	return ""
}

func (x *CreateKonsumenRequest) GetFotoSelfie() string {
	if x != nil {
		return x.FotoSelfie
	}
	return ""
}

func (x *CreateKonsumenRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateKonsumenRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateKonsumenRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateKonsumenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdKonsumen string `protobuf:"bytes,1,opt,name=IdKonsumen,json=id_konsumen,proto3" json:"IdKonsumen,omitempty"`
}

func (x *CreateKonsumenResponse) Reset() {
	*x = CreateKonsumenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKonsumenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKonsumenResponse) ProtoMessage() {}

func (x *CreateKonsumenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKonsumenResponse.ProtoReflect.Descriptor instead.
func (*CreateKonsumenResponse) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{3}
}

func (x *CreateKonsumenResponse) GetIdKonsumen() string {
	if x != nil {
		return x.IdKonsumen
	}
	return ""
}

type CreateLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdKonsumen  string `protobuf:"bytes,1,opt,name=IdKonsumen,json=id_konsumen,proto3" json:"IdKonsumen,omitempty"`
	Tenor       uint32 `protobuf:"varint,2,opt,name=Tenor,json=tenor,proto3" json:"Tenor,omitempty"`
	BatasKredit uint64 `protobuf:"varint,3,opt,name=BatasKredit,json=batas_kredit,proto3" json:"BatasKredit,omitempty"`
}

func (x *CreateLimitRequest) Reset() {
	*x = CreateLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLimitRequest) ProtoMessage() {}

func (x *CreateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLimitRequest.ProtoReflect.Descriptor instead.
func (*CreateLimitRequest) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLimitRequest) GetIdKonsumen() string {
	if x != nil {
		return x.IdKonsumen
	}
	return ""
}

func (x *CreateLimitRequest) GetTenor() uint32 {
	if x != nil {
		return x.Tenor
	}
	return 0
}

func (x *CreateLimitRequest) GetBatasKredit() uint64 {
	if x != nil {
		return x.BatasKredit
	}
	return 0
}

type CreateLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdLimit string `protobuf:"bytes,1,opt,name=IdLimit,json=id_limit,proto3" json:"IdLimit,omitempty"`
}

func (x *CreateLimitResponse) Reset() {
	*x = CreateLimitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLimitResponse) ProtoMessage() {}

func (x *CreateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLimitResponse.ProtoReflect.Descriptor instead.
func (*CreateLimitResponse) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{5}
}

func (x *CreateLimitResponse) GetIdLimit() string {
	if x != nil {
		return x.IdLimit
	}
	return ""
}

type GetLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdLimit    string `protobuf:"bytes,1,opt,name=IdLimit,json=id_limit,proto3" json:"IdLimit,omitempty"`
	IdKonsumen string `protobuf:"bytes,2,opt,name=IdKonsumen,json=id_konsumen,proto3" json:"IdKonsumen,omitempty"`
}

func (x *GetLimitRequest) Reset() {
	*x = GetLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitRequest) ProtoMessage() {}

func (x *GetLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitRequest.ProtoReflect.Descriptor instead.
func (*GetLimitRequest) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetLimitRequest) GetIdLimit() string {
	if x != nil {
		return x.IdLimit
	}
	return ""
}

func (x *GetLimitRequest) GetIdKonsumen() string {
	if x != nil {
		return x.IdKonsumen
	}
	return ""
}

type GetLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdLimit     string `protobuf:"bytes,1,opt,name=IdLimit,json=id_limit,proto3" json:"IdLimit,omitempty"`
	IdKonsumen  string `protobuf:"bytes,2,opt,name=IdKonsumen,json=id_konsumen,proto3" json:"IdKonsumen,omitempty"`
	Tenor       uint32 `protobuf:"varint,3,opt,name=Tenor,json=tenor,proto3" json:"Tenor,omitempty"`
	BatasKredit uint64 `protobuf:"varint,4,opt,name=BatasKredit,json=batas_kredit,proto3" json:"BatasKredit,omitempty"`
}

func (x *GetLimitResponse) Reset() {
	*x = GetLimitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitResponse) ProtoMessage() {}

func (x *GetLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitResponse.ProtoReflect.Descriptor instead.
func (*GetLimitResponse) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetLimitResponse) GetIdLimit() string {
	if x != nil {
		return x.IdLimit
	}
	return ""
}

func (x *GetLimitResponse) GetIdKonsumen() string {
	if x != nil {
		return x.IdKonsumen
	}
	return ""
}

func (x *GetLimitResponse) GetTenor() uint32 {
	if x != nil {
		return x.Tenor
	}
	return 0
}

func (x *GetLimitResponse) GetBatasKredit() uint64 {
	if x != nil {
		return x.BatasKredit
	}
	return 0
}

type CreateTransaksiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdKonsumen       string               `protobuf:"bytes,2,opt,name=IdKonsumen,json=id_konsumen,proto3" json:"IdKonsumen,omitempty"`
	NomorKontrak     string               `protobuf:"bytes,3,opt,name=NomorKontrak,json=nomor_kontrak,proto3" json:"NomorKontrak,omitempty"`
	TanggalTransaksi *timestamp.Timestamp `protobuf:"bytes,4,opt,name=TanggalTransaksi,json=tanggal_transaksi,proto3" json:"TanggalTransaksi,omitempty"`
	Otr              uint64               `protobuf:"varint,5,opt,name=Otr,json=otr,proto3" json:"Otr,omitempty"`
	AdminFee         uint64               `protobuf:"varint,6,opt,name=AdminFee,json=admin_fee,proto3" json:"AdminFee,omitempty"`
	JumlahCicilan    uint64               `protobuf:"varint,7,opt,name=JumlahCicilan,json=jumlah_cicilan,proto3" json:"JumlahCicilan,omitempty"`
	JumlahBunga      uint64               `protobuf:"varint,8,opt,name=JumlahBunga,json=jumlah_bunga,proto3" json:"JumlahBunga,omitempty"`
	NamaAsset        string               `protobuf:"bytes,9,opt,name=NamaAsset,json=nama_asset,proto3" json:"NamaAsset,omitempty"`
	JenisTransaksi   string               `protobuf:"bytes,10,opt,name=JenisTransaksi,json=jenis_transaksi,proto3" json:"JenisTransaksi,omitempty"`
}

func (x *CreateTransaksiRequest) Reset() {
	*x = CreateTransaksiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTransaksiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransaksiRequest) ProtoMessage() {}

func (x *CreateTransaksiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransaksiRequest.ProtoReflect.Descriptor instead.
func (*CreateTransaksiRequest) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTransaksiRequest) GetIdKonsumen() string {
	if x != nil {
		return x.IdKonsumen
	}
	return ""
}

func (x *CreateTransaksiRequest) GetNomorKontrak() string {
	if x != nil {
		return x.NomorKontrak
	}
	return ""
}

func (x *CreateTransaksiRequest) GetTanggalTransaksi() *timestamp.Timestamp {
	if x != nil {
		return x.TanggalTransaksi
	}
	return nil
}

func (x *CreateTransaksiRequest) GetOtr() uint64 {
	if x != nil {
		return x.Otr
	}
	return 0
}

func (x *CreateTransaksiRequest) GetAdminFee() uint64 {
	if x != nil {
		return x.AdminFee
	}
	return 0
}

func (x *CreateTransaksiRequest) GetJumlahCicilan() uint64 {
	if x != nil {
		return x.JumlahCicilan
	}
	return 0
}

func (x *CreateTransaksiRequest) GetJumlahBunga() uint64 {
	if x != nil {
		return x.JumlahBunga
	}
	return 0
}

func (x *CreateTransaksiRequest) GetNamaAsset() string {
	if x != nil {
		return x.NamaAsset
	}
	return ""
}

func (x *CreateTransaksiRequest) GetJenisTransaksi() string {
	if x != nil {
		return x.JenisTransaksi
	}
	return ""
}

type CreateTransaksiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdTransaksi string `protobuf:"bytes,1,opt,name=IdTransaksi,json=id_transaksi,proto3" json:"IdTransaksi,omitempty"`
}

func (x *CreateTransaksiResponse) Reset() {
	*x = CreateTransaksiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTransaksiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransaksiResponse) ProtoMessage() {}

func (x *CreateTransaksiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransaksiResponse.ProtoReflect.Descriptor instead.
func (*CreateTransaksiResponse) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTransaksiResponse) GetIdTransaksi() string {
	if x != nil {
		return x.IdTransaksi
	}
	return ""
}

type GetTransaksiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdTransaksi string `protobuf:"bytes,1,opt,name=IdTransaksi,json=id_transaksi,proto3" json:"IdTransaksi,omitempty"`
}

func (x *GetTransaksiRequest) Reset() {
	*x = GetTransaksiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransaksiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransaksiRequest) ProtoMessage() {}

func (x *GetTransaksiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransaksiRequest.ProtoReflect.Descriptor instead.
func (*GetTransaksiRequest) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{10}
}

func (x *GetTransaksiRequest) GetIdTransaksi() string {
	if x != nil {
		return x.IdTransaksi
	}
	return ""
}

type GetTransaksiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdTransaksi      string               `protobuf:"bytes,1,opt,name=IdTransaksi,json=id_transaksi,proto3" json:"IdTransaksi,omitempty"`
	IdKonsumen       string               `protobuf:"bytes,2,opt,name=IdKonsumen,json=id_konsumen,proto3" json:"IdKonsumen,omitempty"`
	NomorKontrak     string               `protobuf:"bytes,3,opt,name=NomorKontrak,json=nomor_kontrak,proto3" json:"NomorKontrak,omitempty"`
	TanggalTransaksi *timestamp.Timestamp `protobuf:"bytes,4,opt,name=TanggalTransaksi,json=tanggal_transaksi,proto3" json:"TanggalTransaksi,omitempty"`
	Otr              uint64               `protobuf:"varint,5,opt,name=Otr,json=otr,proto3" json:"Otr,omitempty"`
	AdminFee         uint64               `protobuf:"varint,6,opt,name=AdminFee,json=admin_fee,proto3" json:"AdminFee,omitempty"`
	JumlahCicilan    uint64               `protobuf:"varint,7,opt,name=JumlahCicilan,json=jumlah_cicilan,proto3" json:"JumlahCicilan,omitempty"`
	JumlahBunga      uint64               `protobuf:"varint,8,opt,name=JumlahBunga,json=jumlah_bunga,proto3" json:"JumlahBunga,omitempty"`
	NamaAsset        string               `protobuf:"bytes,9,opt,name=NamaAsset,json=nama_asset,proto3" json:"NamaAsset,omitempty"`
	JenisTransaksi   string               `protobuf:"bytes,10,opt,name=JenisTransaksi,json=jenis_transaksi,proto3" json:"JenisTransaksi,omitempty"`
}

func (x *GetTransaksiResponse) Reset() {
	*x = GetTransaksiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kredit_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransaksiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransaksiResponse) ProtoMessage() {}

func (x *GetTransaksiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kredit_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransaksiResponse.ProtoReflect.Descriptor instead.
func (*GetTransaksiResponse) Descriptor() ([]byte, []int) {
	return file_kredit_message_proto_rawDescGZIP(), []int{11}
}

func (x *GetTransaksiResponse) GetIdTransaksi() string {
	if x != nil {
		return x.IdTransaksi
	}
	return ""
}

func (x *GetTransaksiResponse) GetIdKonsumen() string {
	if x != nil {
		return x.IdKonsumen
	}
	return ""
}

func (x *GetTransaksiResponse) GetNomorKontrak() string {
	if x != nil {
		return x.NomorKontrak
	}
	return ""
}

func (x *GetTransaksiResponse) GetTanggalTransaksi() *timestamp.Timestamp {
	if x != nil {
		return x.TanggalTransaksi
	}
	return nil
}

func (x *GetTransaksiResponse) GetOtr() uint64 {
	if x != nil {
		return x.Otr
	}
	return 0
}

func (x *GetTransaksiResponse) GetAdminFee() uint64 {
	if x != nil {
		return x.AdminFee
	}
	return 0
}

func (x *GetTransaksiResponse) GetJumlahCicilan() uint64 {
	if x != nil {
		return x.JumlahCicilan
	}
	return 0
}

func (x *GetTransaksiResponse) GetJumlahBunga() uint64 {
	if x != nil {
		return x.JumlahBunga
	}
	return 0
}

func (x *GetTransaksiResponse) GetNamaAsset() string {
	if x != nil {
		return x.NamaAsset
	}
	return ""
}

func (x *GetTransaksiResponse) GetJenisTransaksi() string {
	if x != nil {
		return x.JenisTransaksi
	}
	return ""
}

var File_kredit_message_proto protoreflect.FileDescriptor

var file_kredit_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6b, 0x72, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14,
	0x0a, 0x12, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x13, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0xdf, 0x02, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x69, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x6b, 0x12, 0x1b, 0x0a, 0x08, 0x46,
	0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x4c, 0x65, 0x67, 0x61,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x67,
	0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x61, 0x6a, 0x69, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x67, 0x61, 0x6a, 0x69, 0x12, 0x21, 0x0a, 0x0b, 0x54,
	0x65, 0x6d, 0x70, 0x61, 0x74, 0x4c, 0x61, 0x68, 0x69, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x61, 0x74, 0x5f, 0x6c, 0x61, 0x68, 0x69, 0x72, 0x12, 0x3f,
	0x0a, 0x0c, 0x54, 0x61, 0x6e, 0x67, 0x67, 0x61, 0x6c, 0x4c, 0x61, 0x68, 0x69, 0x72, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0d, 0x74, 0x61, 0x6e, 0x67, 0x67, 0x61, 0x6c, 0x5f, 0x6c, 0x61, 0x68, 0x69, 0x72, 0x12,
	0x19, 0x0a, 0x07, 0x46, 0x6f, 0x74, 0x6f, 0x4b, 0x74, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x6f, 0x74, 0x6f, 0x5f, 0x6b, 0x74, 0x70, 0x12, 0x1f, 0x0a, 0x0a, 0x46, 0x6f,
	0x74, 0x6f, 0x53, 0x65, 0x6c, 0x66, 0x69, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x66, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x65, 0x6c, 0x66, 0x69, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x52,
	0x6f, 0x6c, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x39, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x49,
	0x64, 0x4b, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x69, 0x64, 0x5f, 0x6b, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x6e, 0x22, 0x6e, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x49, 0x64, 0x4b, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x64, 0x5f, 0x6b, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x65, 0x6e, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x74, 0x65, 0x6e, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0b, 0x42, 0x61, 0x74,
	0x61, 0x73, 0x4b, 0x72, 0x65, 0x64, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x62, 0x61, 0x74, 0x61, 0x73, 0x5f, 0x6b, 0x72, 0x65, 0x64, 0x69, 0x74, 0x22, 0x30, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x49, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x4d,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x07, 0x49, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1f, 0x0a, 0x0a,
	0x49, 0x64, 0x4b, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x69, 0x64, 0x5f, 0x6b, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x6e, 0x22, 0x87, 0x01,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x49, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1f, 0x0a,
	0x0a, 0x49, 0x64, 0x4b, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x69, 0x64, 0x5f, 0x6b, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x65, 0x6e, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74,
	0x65, 0x6e, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x61, 0x73, 0x4b, 0x72, 0x65,
	0x64, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x62, 0x61, 0x74, 0x61, 0x73,
	0x5f, 0x6b, 0x72, 0x65, 0x64, 0x69, 0x74, 0x22, 0xe8, 0x02, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x49, 0x64, 0x4b, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x64, 0x5f, 0x6b, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0c, 0x4e, 0x6f, 0x6d, 0x6f, 0x72, 0x4b, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x6f, 0x6d, 0x6f, 0x72,
	0x5f, 0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x6b, 0x12, 0x47, 0x0a, 0x10, 0x54, 0x61, 0x6e, 0x67,
	0x67, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x11,
	0x74, 0x61, 0x6e, 0x67, 0x67, 0x61, 0x6c, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73,
	0x69, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x74, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x6f, 0x74, 0x72, 0x12, 0x1b, 0x0a, 0x08, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x65, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x66, 0x65, 0x65,
	0x12, 0x25, 0x0a, 0x0d, 0x4a, 0x75, 0x6d, 0x6c, 0x61, 0x68, 0x43, 0x69, 0x63, 0x69, 0x6c, 0x61,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6a, 0x75, 0x6d, 0x6c, 0x61, 0x68, 0x5f,
	0x63, 0x69, 0x63, 0x69, 0x6c, 0x61, 0x6e, 0x12, 0x21, 0x0a, 0x0b, 0x4a, 0x75, 0x6d, 0x6c, 0x61,
	0x68, 0x42, 0x75, 0x6e, 0x67, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6a, 0x75,
	0x6d, 0x6c, 0x61, 0x68, 0x5f, 0x62, 0x75, 0x6e, 0x67, 0x61, 0x12, 0x1d, 0x0a, 0x09, 0x4e, 0x61,
	0x6d, 0x61, 0x41, 0x73, 0x73, 0x65, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e,
	0x61, 0x6d, 0x61, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x0e, 0x4a, 0x65, 0x6e,
	0x69, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x6a, 0x65, 0x6e, 0x69, 0x73, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b,
	0x73, 0x69, 0x22, 0x3c, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x6b, 0x73, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x0b, 0x49, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x69, 0x64, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69,
	0x22, 0x38, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0b, 0x49, 0x64, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x64,
	0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x22, 0x89, 0x03, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x49, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b,
	0x73, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x64, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x12, 0x1f, 0x0a, 0x0a, 0x49, 0x64, 0x4b, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x64, 0x5f, 0x6b,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0c, 0x4e, 0x6f, 0x6d, 0x6f, 0x72,
	0x4b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e,
	0x6f, 0x6d, 0x6f, 0x72, 0x5f, 0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x6b, 0x12, 0x47, 0x0a, 0x10,
	0x54, 0x61, 0x6e, 0x67, 0x67, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x11, 0x74, 0x61, 0x6e, 0x67, 0x67, 0x61, 0x6c, 0x5f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x6b, 0x73, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x74, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x6f, 0x74, 0x72, 0x12, 0x1b, 0x0a, 0x08, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x46, 0x65, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x5f, 0x66, 0x65, 0x65, 0x12, 0x25, 0x0a, 0x0d, 0x4a, 0x75, 0x6d, 0x6c, 0x61, 0x68, 0x43, 0x69,
	0x63, 0x69, 0x6c, 0x61, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6a, 0x75, 0x6d,
	0x6c, 0x61, 0x68, 0x5f, 0x63, 0x69, 0x63, 0x69, 0x6c, 0x61, 0x6e, 0x12, 0x21, 0x0a, 0x0b, 0x4a,
	0x75, 0x6d, 0x6c, 0x61, 0x68, 0x42, 0x75, 0x6e, 0x67, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x6a, 0x75, 0x6d, 0x6c, 0x61, 0x68, 0x5f, 0x62, 0x75, 0x6e, 0x67, 0x61, 0x12, 0x1d,
	0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x61, 0x41, 0x73, 0x73, 0x65, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x61, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x12, 0x27, 0x0a,
	0x0e, 0x4a, 0x65, 0x6e, 0x69, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6a, 0x65, 0x6e, 0x69, 0x73, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x30, 0x78, 0x35, 0x77, 0x34, 0x2f, 0x6b, 0x72, 0x65, 0x64, 0x69,
	0x74, 0x2d, 0x70, 0x6c, 0x75, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kredit_message_proto_rawDescOnce sync.Once
	file_kredit_message_proto_rawDescData = file_kredit_message_proto_rawDesc
)

func file_kredit_message_proto_rawDescGZIP() []byte {
	file_kredit_message_proto_rawDescOnce.Do(func() {
		file_kredit_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_kredit_message_proto_rawDescData)
	})
	return file_kredit_message_proto_rawDescData
}

var file_kredit_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kredit_message_proto_goTypes = []interface{}{
	(*HealthCheckRequest)(nil),      // 0: proto.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 1: proto.HealthCheckResponse
	(*CreateKonsumenRequest)(nil),   // 2: proto.CreateKonsumenRequest
	(*CreateKonsumenResponse)(nil),  // 3: proto.CreateKonsumenResponse
	(*CreateLimitRequest)(nil),      // 4: proto.CreateLimitRequest
	(*CreateLimitResponse)(nil),     // 5: proto.CreateLimitResponse
	(*GetLimitRequest)(nil),         // 6: proto.GetLimitRequest
	(*GetLimitResponse)(nil),        // 7: proto.GetLimitResponse
	(*CreateTransaksiRequest)(nil),  // 8: proto.CreateTransaksiRequest
	(*CreateTransaksiResponse)(nil), // 9: proto.CreateTransaksiResponse
	(*GetTransaksiRequest)(nil),     // 10: proto.GetTransaksiRequest
	(*GetTransaksiResponse)(nil),    // 11: proto.GetTransaksiResponse
	(*timestamp.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_kredit_message_proto_depIdxs = []int32{
	12, // 0: proto.CreateKonsumenRequest.TanggalLahir:type_name -> google.protobuf.Timestamp
	12, // 1: proto.CreateTransaksiRequest.TanggalTransaksi:type_name -> google.protobuf.Timestamp
	12, // 2: proto.GetTransaksiResponse.TanggalTransaksi:type_name -> google.protobuf.Timestamp
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kredit_message_proto_init() }
func file_kredit_message_proto_init() {
	if File_kredit_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kredit_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kredit_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kredit_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKonsumenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kredit_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKonsumenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kredit_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kredit_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLimitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kredit_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kredit_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLimitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kredit_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTransaksiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kredit_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTransaksiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kredit_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransaksiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kredit_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransaksiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kredit_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kredit_message_proto_goTypes,
		DependencyIndexes: file_kredit_message_proto_depIdxs,
		MessageInfos:      file_kredit_message_proto_msgTypes,
	}.Build()
	File_kredit_message_proto = out.File
	file_kredit_message_proto_rawDesc = nil
	file_kredit_message_proto_goTypes = nil
	file_kredit_message_proto_depIdxs = nil
}
