// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: writer.proto

package writerService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WriterService_CreateKonsumen_FullMethodName  = "/writerService.writerService/CreateKonsumen"
	WriterService_CreateLimit_FullMethodName     = "/writerService.writerService/CreateLimit"
	WriterService_CreateTransaksi_FullMethodName = "/writerService.writerService/CreateTransaksi"
	WriterService_GetLimit_FullMethodName        = "/writerService.writerService/GetLimit"
	WriterService_GetTransaksi_FullMethodName    = "/writerService.writerService/GetTransaksi"
)

// WriterServiceClient is the client API for WriterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WriterServiceClient interface {
	CreateKonsumen(ctx context.Context, in *CreateKonsumenRequest, opts ...grpc.CallOption) (*CreateKonsumenResponse, error)
	CreateLimit(ctx context.Context, in *CreateLimitRequest, opts ...grpc.CallOption) (*CreateLimitResponse, error)
	CreateTransaksi(ctx context.Context, in *CreateTransaksiRequest, opts ...grpc.CallOption) (*CreateTransaksiResponse, error)
	GetLimit(ctx context.Context, in *GetLimitRequest, opts ...grpc.CallOption) (*GetLimitResponse, error)
	GetTransaksi(ctx context.Context, in *GetTransaksiRequest, opts ...grpc.CallOption) (*GetTransaksiResponse, error)
}

type writerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWriterServiceClient(cc grpc.ClientConnInterface) WriterServiceClient {
	return &writerServiceClient{cc}
}

func (c *writerServiceClient) CreateKonsumen(ctx context.Context, in *CreateKonsumenRequest, opts ...grpc.CallOption) (*CreateKonsumenResponse, error) {
	out := new(CreateKonsumenResponse)
	err := c.cc.Invoke(ctx, WriterService_CreateKonsumen_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writerServiceClient) CreateLimit(ctx context.Context, in *CreateLimitRequest, opts ...grpc.CallOption) (*CreateLimitResponse, error) {
	out := new(CreateLimitResponse)
	err := c.cc.Invoke(ctx, WriterService_CreateLimit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writerServiceClient) CreateTransaksi(ctx context.Context, in *CreateTransaksiRequest, opts ...grpc.CallOption) (*CreateTransaksiResponse, error) {
	out := new(CreateTransaksiResponse)
	err := c.cc.Invoke(ctx, WriterService_CreateTransaksi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writerServiceClient) GetLimit(ctx context.Context, in *GetLimitRequest, opts ...grpc.CallOption) (*GetLimitResponse, error) {
	out := new(GetLimitResponse)
	err := c.cc.Invoke(ctx, WriterService_GetLimit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writerServiceClient) GetTransaksi(ctx context.Context, in *GetTransaksiRequest, opts ...grpc.CallOption) (*GetTransaksiResponse, error) {
	out := new(GetTransaksiResponse)
	err := c.cc.Invoke(ctx, WriterService_GetTransaksi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriterServiceServer is the server API for WriterService service.
// All implementations should embed UnimplementedWriterServiceServer
// for forward compatibility
type WriterServiceServer interface {
	CreateKonsumen(context.Context, *CreateKonsumenRequest) (*CreateKonsumenResponse, error)
	CreateLimit(context.Context, *CreateLimitRequest) (*CreateLimitResponse, error)
	CreateTransaksi(context.Context, *CreateTransaksiRequest) (*CreateTransaksiResponse, error)
	GetLimit(context.Context, *GetLimitRequest) (*GetLimitResponse, error)
	GetTransaksi(context.Context, *GetTransaksiRequest) (*GetTransaksiResponse, error)
}

// UnimplementedWriterServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWriterServiceServer struct {
}

func (UnimplementedWriterServiceServer) CreateKonsumen(context.Context, *CreateKonsumenRequest) (*CreateKonsumenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKonsumen not implemented")
}
func (UnimplementedWriterServiceServer) CreateLimit(context.Context, *CreateLimitRequest) (*CreateLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLimit not implemented")
}
func (UnimplementedWriterServiceServer) CreateTransaksi(context.Context, *CreateTransaksiRequest) (*CreateTransaksiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaksi not implemented")
}
func (UnimplementedWriterServiceServer) GetLimit(context.Context, *GetLimitRequest) (*GetLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLimit not implemented")
}
func (UnimplementedWriterServiceServer) GetTransaksi(context.Context, *GetTransaksiRequest) (*GetTransaksiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaksi not implemented")
}

// UnsafeWriterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WriterServiceServer will
// result in compilation errors.
type UnsafeWriterServiceServer interface {
	mustEmbedUnimplementedWriterServiceServer()
}

func RegisterWriterServiceServer(s grpc.ServiceRegistrar, srv WriterServiceServer) {
	s.RegisterService(&WriterService_ServiceDesc, srv)
}

func _WriterService_CreateKonsumen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKonsumenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).CreateKonsumen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_CreateKonsumen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).CreateKonsumen(ctx, req.(*CreateKonsumenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriterService_CreateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).CreateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_CreateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).CreateLimit(ctx, req.(*CreateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriterService_CreateTransaksi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransaksiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).CreateTransaksi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_CreateTransaksi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).CreateTransaksi(ctx, req.(*CreateTransaksiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriterService_GetLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).GetLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_GetLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).GetLimit(ctx, req.(*GetLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriterService_GetTransaksi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransaksiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServiceServer).GetTransaksi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriterService_GetTransaksi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServiceServer).GetTransaksi(ctx, req.(*GetTransaksiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WriterService_ServiceDesc is the grpc.ServiceDesc for WriterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WriterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "writerService.writerService",
	HandlerType: (*WriterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKonsumen",
			Handler:    _WriterService_CreateKonsumen_Handler,
		},
		{
			MethodName: "CreateLimit",
			Handler:    _WriterService_CreateLimit_Handler,
		},
		{
			MethodName: "CreateTransaksi",
			Handler:    _WriterService_CreateTransaksi_Handler,
		},
		{
			MethodName: "GetLimit",
			Handler:    _WriterService_GetLimit_Handler,
		},
		{
			MethodName: "GetTransaksi",
			Handler:    _WriterService_GetTransaksi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "writer.proto",
}
