serviceName: reader_service
grpcServer:
  port: :5003
logger:
  encoding: json
  level: debug
  ouputPath: logs
  errorPath: logs
kafka:
  brokers: ["localhost:9092"]
  groupID: writer_microservice_consumer
  initTopics: true
kafkaTopics:
  konsumenCreated:
    topicName: konsumen_created
    partitions: 10
    replicationFactor: 1
  limitCreated:
    topicName: limit_created
    partitions: 10
    replicationFactor: 1
  transaksiCreated:
    topicName: transaksi_created
    partitions: 10
    replicationFactor: 1
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  poolSize: 300
mongo:
  uri: "mongodb://localhost:27017"
  user: admin
  password: admin
  db: kredit
mongoCollections:
  products: kredit
serviceSettings:
  redisKreditPrefixKey: "reader:kredit"
