basePath: /api/v1
definitions:
  dto.CreateKonsumenRequestDto:
    properties:
      email:
        maxLength: 255
        minLength: 0
        type: string
      foto_ktp:
        type: string
      foto_selfie:
        type: string
      full_name:
        maxLength: 255
        minLength: 0
        type: string
      gaji:
        minimum: 0
        type: number
      id_konsumen:
        type: string
      legal_name:
        maxLength: 255
        minLength: 0
        type: string
      nik:
        maxLength: 255
        minLength: 0
        type: string
      password:
        maxLength: 255
        minLength: 0
        type: string
      tanggal_lahir:
        type: string
      tempat_lahir:
        maxLength: 255
        minLength: 0
        type: string
    required:
    - email
    - foto_ktp
    - foto_selfie
    - full_name
    - gaji
    - id_konsumen
    - legal_name
    - nik
    - password
    - tanggal_lahir
    - tempat_lahir
    type: object
  dto.CreateKonsumenResponseDto:
    properties:
      id_konsumen:
        type: string
    required:
    - id_konsumen
    type: object
  dto.CreateLimitRequestDto:
    properties:
      batas_kredit:
        minimum: 0
        type: number
      id_konsumen:
        type: string
      id_limit:
        type: string
      tenor:
        minimum: 0
        type: integer
    required:
    - batas_kredit
    - id_konsumen
    - id_limit
    - tenor
    type: object
  dto.CreateLimitResponseDto:
    properties:
      id_limit:
        type: string
    required:
    - id_limit
    type: object
  dto.CreateTransaksiRequestDto:
    properties:
      admin_fee:
        minimum: 0
        type: number
      id_konsumen:
        type: string
      id_transaksi:
        type: string
      jenis_transaksi:
        maxLength: 255
        minLength: 0
        type: string
      jumlah_bunga:
        minimum: 0
        type: number
      jumlah_cicilan:
        minimum: 0
        type: number
      nama_asset:
        maxLength: 255
        minLength: 0
        type: string
      nomor_kontrak:
        maxLength: 255
        minLength: 0
        type: string
      otr:
        type: integer
      tanggal_transaksi:
        type: string
    required:
    - admin_fee
    - id_konsumen
    - id_transaksi
    - jenis_transaksi
    - jumlah_bunga
    - jumlah_cicilan
    - nama_asset
    - nomor_kontrak
    - otr
    - tanggal_transaksi
    type: object
  dto.CreateTransaksiResponseDto:
    properties:
      id_transaksi:
        type: string
    required:
    - id_transaksi
    type: object
  dto.GetLimitResponseDto:
    properties:
      batas_kredit:
        minimum: 0
        type: number
      id_konsumen:
        type: string
      id_limit:
        type: string
      tenor:
        minimum: 0
        type: integer
    required:
    - batas_kredit
    - id_konsumen
    - id_limit
    - tenor
    type: object
  dto.GetTransaksiResponseDto:
    properties:
      admin_fee:
        minimum: 0
        type: number
      id_konsumen:
        type: string
      id_transaksi:
        type: string
      jenis_transaksi:
        maxLength: 255
        minLength: 0
        type: string
      jumlah_bunga:
        minimum: 0
        type: number
      jumlah_cicilan:
        minimum: 0
        type: number
      nama_asset:
        maxLength: 255
        minLength: 0
        type: string
      nomor_kontrak:
        maxLength: 255
        minLength: 0
        type: string
      otr:
        type: integer
      tanggal_transaksi:
        type: string
    required:
    - admin_fee
    - id_konsumen
    - id_transaksi
    - jenis_transaksi
    - jumlah_bunga
    - jumlah_cicilan
    - nama_asset
    - nomor_kontrak
    - otr
    - tanggal_transaksi
    type: object
host: localhost:5001
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample API on Kredit Plus Microservice.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API Gateway Kredit Plus
  version: "1.0"
paths:
  /konsumen:
    post:
      consumes:
      - application/json
      description: Create new konsumen item
      parameters:
      - description: Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateKonsumenRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateKonsumenResponseDto'
      summary: Create konsumen
      tags:
      - Kredit
  /limit:
    post:
      consumes:
      - application/json
      description: Create new limit item
      parameters:
      - description: Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateLimitRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateLimitResponseDto'
      summary: Create limit
      tags:
      - Kredit
  /limit/{id}:
    get:
      consumes:
      - application/json
      description: Get limit by id
      parameters:
      - description: Id Limit
        in: path
        name: id_limit
        required: true
        type: string
      - description: Id Konsumen
        in: path
        name: id_konsumen
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetLimitResponseDto'
      summary: Get limit
      tags:
      - Kredit
  /transaksi:
    post:
      consumes:
      - application/json
      description: Create new transaksi item
      parameters:
      - description: Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTransaksiRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateTransaksiResponseDto'
      summary: Create transaksi
      tags:
      - Kredit
  /transaksi/{id}:
    get:
      consumes:
      - application/json
      description: Get transaksi by id
      parameters:
      - description: Id Transaksi
        in: path
        name: id_transaksi
        required: true
        type: string
      - description: Id Konsumen
        in: path
        name: id_konsumen
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetTransaksiResponseDto'
      summary: Get transaksi
      tags:
      - Kredit
swagger: "2.0"
